name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build-base
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go-build
      run: |
        go env
        go get -v github.com/Masterminds/glide
        pwd
        export GOPATH="${PWD}"
        make get-deps
        make build
        
#     - name: Upload artifact
#       uses: actions/upload-artifact@master
#       with:
#         name: prom2click-tools
#         path: **/prom2click
